accepts-transfers=false
allow-flight=true
broadcast-console-to-ops=false
broadcast-rcon-to-ops=false
difficulty=normal
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
gamemode=survival
generate-structures=false
hardcore=false
level-name=world
max-players=2
motd=Monster Maze SOLO 1.21
online-mode=true
player-idle-timeout=0
pvp=false
query.port=25565
server-port=25565
simulation-distance=6
spawn-animals=false
spawn-monsters=false
spawn-npcs=false
view-distance=8
white-list=false
